if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\[\033[01;34m\] \w \$(parse_git_branch)\n\[\033[01;32m\]::\[\033[00m\] "
