#!/usr/bin/env ruby

def _windowlist
  return `lsw`.split("\n")
end

def _isfocusset
  return system "pfw > /dev/null 2>&1"
end

def _setfocus _wid
  system "focus #{_wid}"
end

def _destroy wid
  unless _isfocusset
    _setfocus _windowlist[-1]
  end
end

def _map wid
  unless system "wattr o #{wid} > /dev/null 2>&1"
    _setfocus wid
  end
end

def _create wid
  unless system "wattr o #{wid} > /dev/null 2>&1"
    _setfocus wid
  end
end

while _in = gets
  _in = _in.split
  action = _in[0]
  wid = _in[1]

  case action
  when "DESTROY"
    _destroy wid
  when "CREATE"
    _create wid
  when "MAP"
    _map wid
  end
end
