#!/bin/bash

INTERNAL=eDP1
EXTERNAL=DP1-1

if xrandr | grep "$EXTERNAL disconnted"; then
  xrandr --output "$EXTERNAL" --off --output "$INTERNAL" --auto
else
  xrandr --output "$INTERNAL" --auto --output "$EXTERNAL" --right-of "$INTERNAL" --auto
fi
